! ------------------------------------------------------------------
! generated by cmc 1.0.0
! vehicle       : ARAC
! variant       : BASE
! revision      : R01
! run id        : 2026-08-27T09-10-39
! source        : FakeVehicle.CATProduct
! source sha256 : None
! measured by   : root at 2026-08-27T09:10:39+00:00
! catia         : {'source': 'fake'}
! work mode     : {'work_mode_value': None, 'verified': True, 'source': 'fake'}
! transform     : catia_vehicle_to_adams_front_wheel_origin
! units         : mm, kg, kg*mm^2
! inertia ref   : origin / product sign 1
! ------------------------------------------------------------------

! Tekerlek Grubu -> .vehicle.ges_wheels.gel_mass
marker modify &
   marker_name = .vehicle.ges_wheels.gel_mass.cm &
   location = 1400.000000, 0.000000, -340.000000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_wheels.gel_mass &
   mass = 248.000000 &
   ixx = 172546000.000000 &
   iyy = 489824800.000000 &
   izz = 658601200.000000 &
   ixy = -0.000000 &
   izx = -3472000.000000 &
   iyz = -0.000000 &
   cm_marker = .vehicle.ges_wheels.gel_mass.cm

! Ön Aks -> .vehicle.ges_front_axle.gel_beam
marker modify &
   marker_name = .vehicle.ges_front_axle.gel_beam.cm &
   location = 10.000000, -13.333333, -323.333333
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_front_axle.gel_beam &
   mass = 210.000000 &
   ixx = 3243333.333333 &
   iyy = 4404166.666667 &
   izz = 4460166.666667 &
   ixy = -28000.000000 &
   izx = 14000.000000 &
   iyz = -37333.333333 &
   cm_marker = .vehicle.ges_front_axle.gel_beam.cm

! Ön Süspansiyon -> .vehicle.ges_front_susp.gel_mass
marker modify &
   marker_name = .vehicle.ges_front_susp.gel_mass.cm &
   location = 5.000000, 0.000000, -220.000000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_front_susp.gel_mass &
   mass = 180.000000 &
   ixx = 67500000.000000 &
   iyy = 3750000.000000 &
   izz = 68550000.000000 &
   ixy = -0.000000 &
   izx = -0.000000 &
   iyz = -0.000000 &
   cm_marker = .vehicle.ges_front_susp.gel_mass.cm

! Arka Aks -> .vehicle.ges_rear_axle.gel_beam
marker modify &
   marker_name = .vehicle.ges_rear_axle.gel_beam.cm &
   location = 2800.625000, -9.375000, -353.750000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_rear_axle.gel_beam &
   mass = 320.000000 &
   ixx = 4889375.000000 &
   iyy = 6756041.666667 &
   izz = 6790416.666667 &
   ixy = 61875.000000 &
   izx = -41250.000000 &
   iyz = -41250.000000 &
   cm_marker = .vehicle.ges_rear_axle.gel_beam.cm

! Arka Süspansiyon -> .vehicle.ges_rear_susp.gel_mass
marker modify &
   marker_name = .vehicle.ges_rear_susp.gel_mass.cm &
   location = 2805.000000, 0.000000, -270.000000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_rear_susp.gel_mass &
   mass = 178.489000 &
   ixx = 69093091.900000 &
   iyy = 3718520.833333 &
   izz = 70134277.733333 &
   ixy = -0.000000 &
   izx = -0.000000 &
   iyz = -0.000000 &
   cm_marker = .vehicle.ges_rear_susp.gel_mass.cm

! Direksiyon Kolon -> .vehicle.ges_steering.gel_column
marker modify &
   marker_name = .vehicle.ges_steering.gel_column.cm &
   location = 430.000000, -360.000000, 260.000000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_steering.gel_column &
   mass = 18.000000 &
   ixx = 19200.000000 &
   iyy = 549600.000000 &
   izz = 549600.000000 &
   ixy = 0.000000 &
   izx = -0.000000 &
   iyz = 0.000000 &
   cm_marker = .vehicle.ges_steering.gel_column.cm

! Direksiyon Bağlantı -> .vehicle.ges_steering.gel_linkage
marker modify &
   marker_name = .vehicle.ges_steering.gel_linkage.cm &
   location = 220.000000, -20.000000, -160.000000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_steering.gel_linkage &
   mass = 12.000000 &
   ixx = 7200.000000 &
   iyy = 643600.000000 &
   izz = 643600.000000 &
   ixy = -0.000000 &
   izx = -0.000000 &
   iyz = -0.000000 &
   cm_marker = .vehicle.ges_steering.gel_linkage.cm

! Şase -> .vehicle.ges_body.gel_chassis
marker modify &
   marker_name = .vehicle.ges_body.gel_chassis.cm &
   location = 1500.000000, 0.000000, -185.000000
part modify rigid_body mass_properties &
   part_name = .vehicle.ges_body.gel_chassis &
   mass = 879.913000 &
   ixx = 300717600.358333 &
   iyy = 335122198.658333 &
   izz = 622597108.366667 &
   ixy = -15838434.000000 &
   izx = -2639739.000000 &
   iyz = 131986.950000 &
   cm_marker = .vehicle.ges_body.gel_chassis.cm

