"use strict";var n=this&&this.__awaiter||function(n,e,t,i){return new(t||(t=Promise))(function(r,o){function a(n){try{u(i.next(n))}catch(n){o(n)}}function l(n){try{u(i.throw(n))}catch(n){o(n)}}function u(n){var e;n.done?r(n.value):(e=n.value,e instanceof t?e:new t(function(n){n(e)})).then(a,l)}u((i=i.apply(n,e||[])).next())})};function e(n){chrome.runtime.sendMessage(n)}function t(n){var e=new Date,t=null;do{t=new Date}while(t-e<n)}function i(n,e){var t=window.location.hostname+";"+window.location.href;try{for(let i of n){const n=new String(i.name);if(n){const r=new String(i.lastModified);t+="|"+n+";"+r+";"+new String(i.size),e.hasAtleastOneValidFile=!0}}}catch(n){console.log(n),e.hasAtleastOneValidFile=!1,t=""}return t}function r(n){if(n.target.files&&n.target.files.length>0){let o={hasAtleastOneValidFile:!1};var r=i(n.target.files,o);o.hasAtleastOneValidFile&&""!=r&&(e(r),t(500))}}function o(n){return new Promise((e,t)=>{n.file(e,t)})}function a(e,t){return n(this,void 0,void 0,function*(){const n=yield o(e),i=new String(n.name);if(i){const e=new String(t+n.name);return i+";"+new String(n.lastModified)+";"+new String(n.size)+";"+e}return null})}function l(n){return new Promise((e,t)=>{n.readEntries(e,t)})}function u(e){return n(this,void 0,void 0,function*(){let n,t=[];do{n=yield l(e),t.push(...n)}while(n.length>0);return t})}function s(e,t){return n(this,void 0,void 0,function*(){var n=e.createReader();const i=yield u(n);return(yield Promise.allSettled(i.map(n=>c(n,t+e.name+"/")))).filter(n=>"fulfilled"===n.status&&null!==n.value).map(n=>n.value).flat()})}function c(e,t){return n(this,void 0,void 0,function*(){return t=t||"",e.isFile?a(e,t):e.isDirectory?s(e,t):null})}function f(i){return n(this,void 0,void 0,function*(){var n=i.dataTransfer.items,r=[];if((yield Promise.allSettled(Array.from(n).map(n=>{const e=n.webkitGetAsEntry();return e?c(e):null}))).forEach(n=>{"fulfilled"===n.status&&n.value&&(Array.isArray(n.value)?r.push(...n.value):r.push(n.value))}),r.length>0){var o=window.location.hostname+";"+window.location.href;e(o+="|"+r.join("|")),t(500)}})}function d(){document.addEventListener("change",r,!0),document.addEventListener("drop",f,!0)}d();
// SIG // Begin signature block
// SIG // MIIpAAYJKoZIhvcNAQcCoIIo8TCCKO0CAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // AL79Yanb5bahc4wSWrpgEH+lMrISwuEYTKcdVWObEKqg
// SIG // gg3SMIIGvDCCBKSgAwIBAgITMwAAAK38IG+LIrCxYAAA
// SIG // AAAArTANBgkqhkiG9w0BAQwFADBiMQswCQYDVQQGEwJV
// SIG // UzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MTMwMQYDVQQDEypBenVyZSBSU0EgUHVibGljIFNlcnZp
// SIG // Y2VzIENvZGUgU2lnbmluZyBQQ0EwHhcNMjUwNjE5MTg1
// SIG // NTU2WhcNMjYwNjE3MTg1NTU2WjCBgjELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEsMCoGA1UEAxMjQXp1cmUgUHVibGljIFNl
// SIG // cnZpY2VzIFJTQSBDb2RlIFNpZ24wggGiMA0GCSqGSIb3
// SIG // DQEBAQUAA4IBjwAwggGKAoIBgQCJl+5LV0eJx7v8/kJZ
// SIG // oOlqngF9pV2cMANu41+rOBcHv7re/N7nncIoz2CMrDfb
// SIG // N+nDZkoTgtuTHIIEu/rmnWTM39WOXLtmQXA7/8dzEvtU
// SIG // 9f9PdmHCmp1rrdIW/rrNMNGPAC9R951A0wqirUR5ja4R
// SIG // PEKFfEtPcQsCtwvM9RsiMyRKc2HCEEXrE+l5FCPyWpxy
// SIG // F9fM+G/lAkpuimw5VpIPdgZnPlMDDzlCauwQbGRVehLO
// SIG // EOQy48tiVW9v+kNbpIaLwZVJAuw/wwhLzcsgz6h2vAgb
// SIG // uRvePiDt1gXXuY0+YQaFysvAX0svl76orrbAUIKlbhXN
// SIG // JTKZNiFJamnylZWxtpjaVE+vQ0yFKXcWozfHD78EcDlo
// SIG // 6quEIp0lzQAtlHW5lbidhLJg9VL88tXST8Fyc6A/CLjF
// SIG // U+nt9SxXHX2mOnxFJSCq1L4faMPNMzALZVARwhtGskoU
// SIG // QM9XSltLbWNdcE9rhXGac8hStpDip9rhTngHxjxGAmce
// SIG // vZIg8V4UhrkCAwEAAaOCAcgwggHEMA4GA1UdDwEB/wQE
// SIG // AwIHgDAfBgNVHSUEGDAWBggrBgEFBQcDAwYKKwYBBAGC
// SIG // N1sBATAdBgNVHQ4EFgQUQISxJf/riX40MloKfgLCK2ZN
// SIG // lEwwVAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jv
// SIG // c29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEW
// SIG // MBQGA1UEBRMNNDY5OTgxKzUwNTMwMjAfBgNVHSMEGDAW
// SIG // gBTxL7qRFnzefVInMfV6+9VYWWk6PTBvBgNVHR8EaDBm
// SIG // MGSgYqBghl5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
// SIG // cGtpb3BzL2NybC9BenVyZSUyMFJTQSUyMFB1YmxpYyUy
// SIG // MFNlcnZpY2VzJTIwQ29kZSUyMFNpZ25pbmclMjBQQ0Eu
// SIG // Y3JsMHwGCCsGAQUFBwEBBHAwbjBsBggrBgEFBQcwAoZg
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
// SIG // ZXJ0cy9BenVyZSUyMFJTQSUyMFB1YmxpYyUyMFNlcnZp
// SIG // Y2VzJTIwQ29kZSUyMFNpZ25pbmclMjBQQ0EuY3J0MAwG
// SIG // A1UdEwEB/wQCMAAwDQYJKoZIhvcNAQEMBQADggIBACKa
// SIG // Fu+q282v2VJbeb0tD6cdvP0hlBx5AlsalCH9p+kBIhod
// SIG // 7HlX0M7wt1/NgDu2yU2uHQt7m45mLKA5vO0zuZpC0LCb
// SIG // QWGkDn/BednxMxk0QGRDt4fCDihbE66jwC9oSue+v2Ns
// SIG // tK2LuYLsnvs/DPoFbSo41uyfapqlKT75knCaFfB/i6mt
// SIG // 2Elp773AXILVuOCFOrEip4g+sVQl1z3lL2+cJV4wHXsT
// SIG // wpm4sx0dilQ6cPRusP2zbl2XkV3zYCqur/76rXb0eAqg
// SIG // tAzsk9SIk2OKHmNRXE4KN2tAoJdogh1cQ6qPiWSenpea
// SIG // vzzL7/XwyrNdP8/84ns4iqqVQPAyc8MZjH3EqF+y/KJV
// SIG // OXbzGBoQju7Ptaj44B38cg4KCFuFU1Qkpijd3CMMy6ZR
// SIG // iMoehWRKsXsnLDMid7GlobkJpsvF/5PWJAC5MktwBrZA
// SIG // Aoz5bZcZUmhkSTau/GK4WdVax+GmDYAY/LanJAXK4S5C
// SIG // odeKJhtp7B2E6qeVd8QtgVEpKdZ24Ws4cB/xK5iTkDO9
// SIG // Z+sV0Y8GSx3kVOJlHWqtC18M0HEZkbJwKeIlbk/8sgcE
// SIG // HNGblgqsCDsCJ34l9B8cRO+WVsOwC4TIL6JZd1JGQTQ3
// SIG // HrkpWIi1Vg0Hkqtkj86XsdUirUgMiSSlTE0MMpi91nV6
// SIG // iVERCggPA1Q9egK2tpBXMIIHDjCCBPagAwIBAgITMwAA
// SIG // AAKyxJOIeFns0wAAAAAAAjANBgkqhkiG9w0BAQwFADBb
// SIG // MQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSwwKgYDVQQDEyNNaWNyb3NvZnQg
// SIG // UlNBIFNlcnZpY2VzIFJvb3QgQ0EgMjAyMTAeFw0yMTA5
// SIG // MDIxNzQxMTlaFw0zNjA5MDIxNzUxMTlaMGIxCzAJBgNV
// SIG // BAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xMzAxBgNVBAMTKkF6dXJlIFJTQSBQdWJsaWMg
// SIG // U2VydmljZXMgQ29kZSBTaWduaW5nIFBDQTCCAiIwDQYJ
// SIG // KoZIhvcNAQEBBQADggIPADCCAgoCggIBAKXd/Sy91nFg
// SIG // seVJOFgeRhVxrcahyp1YGSN0FpOEgEREVb3ND/QgI7I0
// SIG // yd7XG6OE8Vomr5FMxvK8TvJ4Lc6LP9BDz2GSa1M0LlzH
// SIG // KX757/24C0ZndzccA1qQi00+BmmOr4plmxRzTFv4Phdw
// SIG // 8yBPF9GDvClqV8ASvvbitfjaD7dVPOFLb7N7fvt/qWog
// SIG // GN5eis0FXCqVJdmPZZaX2h4iG0otsAhfq8yvSlJ0YwO4
// SIG // i5GDeLQwTsMN1Rf2UAHQKCUYkFsLSQ0mqbaRbDZhB+2p
// SIG // FL/q/c2a6hlHLnapYyfwlNFXkDhwAFWEzfwFHER2oR42
// SIG // UayfN9tsO/p2tWk33CrnHdndJDrIZ6oQ3D+Ngol/TR8B
// SIG // AgXCIM6se6YlLDTsxRwh9QUDq7KVhKy58HGKJUqwgIW0
// SIG // E7cvlzUl0Hft/ebhALZyFDkhof9C5Cq4c/486XLjQq0n
// SIG // buKsFNhQU0yvABR3eohw63Kps66Uma48oE0JmqOxmzrP
// SIG // vrITYcsnByKleiHn+4yq+Ts/KrtqkQwQcuikMPrZwXCt
// SIG // sYkxMUyUn8gr8oew22WDeIQECAM1Cz9TcdJadsrToKqX
// SIG // Qa2bAn/AABAYyogPPONfGvojTI3DlYD42etMa/gPeZJa
// SIG // vX+z7x8d/4eYBnJ9WFSi9q0v+vLOGc3fyM2KQtq5eVbH
// SIG // X5rVyWc6bJ35AgMBAAGjggHCMIIBvjAQBgkrBgEEAYI3
// SIG // FQEEAwIBADAdBgNVHQ4EFgQU8S+6kRZ83n1SJzH1evvV
// SIG // WFlpOj0wVAYDVR0gBE0wSzBJBgRVHSAAMEEwPwYIKwYB
// SIG // BQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTAZBgkrBgEE
// SIG // AYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYw
// SIG // DwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQODLFk
// SIG // ab0tsdVrJqZH6lZOgMPtijBmBgNVHR8EXzBdMFugWaBX
// SIG // hlVodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
// SIG // L2NybC9NaWNyb3NvZnQlMjBSU0ElMjBTZXJ2aWNlcyUy
// SIG // MFJvb3QlMjBDQSUyMDIwMjEuY3JsMHMGCCsGAQUFBwEB
// SIG // BGcwZTBjBggrBgEFBQcwAoZXaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNyb3NvZnQl
// SIG // MjBSU0ElMjBTZXJ2aWNlcyUyMFJvb3QlMjBDQSUyMDIw
// SIG // MjEuY3J0MA0GCSqGSIb3DQEBDAUAA4ICAQBin7PMBnXj
// SIG // nIJ0x++LnudLDWWnZ8dZmJ14DuZfUss/doUThLAM4crr
// SIG // HaTbJoulUUELNd2AnOpX/Z4tenUMT3sjYIdPYyJfIYWP
// SIG // RqfI6Nbz+JVK7RRvn2nl5EEMIuRE6UKS9ZGBbf02a7sb
// SIG // 04E/7BN/NhhrmtS/tVFjfRrrVh9zXku45rqWuCwUTzg3
// SIG // EqxKQ8OGbtjBQtq/Syb/clm5BHsoh3XhMnb9VLv3G1du
// SIG // Nf90FL5/o88XZ4L18nx1lfky2nllY4HIA8PK8AarqAW4
// SIG // iKSTA3EGqn8s/47WtQKT+qED2YbZXVOYL+L7vQDCnFbw
// SIG // hgAx6ucuMz7Ae1rqibg3AjsC7U5M3oA/vqAHDKDA3mdM
// SIG // 5D6L/ZEdQgaG20HhUOSQ+CiQD3TyHSiVCfVMuTv83IiK
// SIG // Cni3LW/23tHC2tbN57rlhMcoyjIi+IVd7j7s41MFBaDw
// SIG // JrmfXn/YM+lR/5QqvO7zWAbbr/XU531v3jr/jBilmrqt
// SIG // 6U/b7y8TXyA9nYxV9iSMFmcbyIi2xgdcAHhxnpXcvcvy
// SIG // FWET6YiJiyeSJZwwJv8gwXiBF+Zh0IHArl6KVsbAdsAT
// SIG // uP1TCEBpPynXZmkviIEWPtnv315ZjTC7nPoOpSnOVaO7
// SIG // wZztrOefZunI5fBxw7mG1oyoRnADZawiFsVo9J/cDu15
// SIG // ErRCfDQRhwSiBTGCGoYwghqCAgEBMHkwYjELMAkGA1UE
// SIG // BhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEzMDEGA1UEAxMqQXp1cmUgUlNBIFB1YmxpYyBT
// SIG // ZXJ2aWNlcyBDb2RlIFNpZ25pbmcgUENBAhMzAAAArfwg
// SIG // b4sisLFgAAAAAACtMA0GCWCGSAFlAwQCAQUAoIGuMBkG
// SIG // CSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQB
// SIG // gjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJ
// SIG // BDEiBCCuaxBtONQcIgnySu8zuUC7znw9gDvFb7tuGM03
// SIG // B4Dc6DBCBgorBgEEAYI3AgEMMTQwMqAUgBIATQBpAGMA
// SIG // cgBvAHMAbwBmAHShGoAYaHR0cDovL3d3dy5taWNyb3Nv
// SIG // ZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBgHOxVc0CXsDm
// SIG // HM1I5MaFCNwrxRqH+18dt3KigG9C6pa2yzurmRibKdxB
// SIG // VWPLolXY0vrrucnWgLVsRPO75O6k8RljS0aKlgLgOIsg
// SIG // +oHlFdgtEuqmlFJ2nEFFygySgBX3BvE48YPXuqnoRgUe
// SIG // DVirrbcj1MWQwJ4mdnGdVy3brVxHIymhCklSGSVU52V7
// SIG // vFFmjaEcvaZ2bX3KbtpAkxZafz+a26KxRqn0k3sBL4l1
// SIG // /ZpSVrOX3ETZkabzy3flfdHBgpgMcn8w/aq/oYjqqq2a
// SIG // CW3AmnYzAvcN+999HyEu2PKW2kLcohclAsM7XFiFErxx
// SIG // jMdXlVaNaE+/GvfzwkNrt+PxXUGropChAvkSxu4C0rPN
// SIG // chbhmbQuR+OXWOh5f18HKmWvmW5L7z9Mja5SYDIG2tqc
// SIG // 7Egk7Eh+cOj5076tWCatNtwEe+uKCe7ergSm3g2Clinn
// SIG // 3Ls9U0GXGqZNvOX0wYghOPsHBXSeD7SyPUZ4YFY4LYB3
// SIG // CU3ECSIHSaksLQAyGKGCF60wghepBgorBgEEAYI3AwMB
// SIG // MYIXmTCCF5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8w
// SIG // DQYJYIZIAWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCC
// SIG // AUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCG
// SIG // SAFlAwQCAQUABCC6+/gy7k+31iPUenxNs6ikPCGRCinU
// SIG // PKtw/l2jT03QUQIGabzV+btGGBMyMDI2MDQwNjIwMjU1
// SIG // MS4xMTNaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
// SIG // UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
// SIG // UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
// SIG // cmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFu
// SIG // ZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5T
// SIG // aGllbGQgVFNTIEVTTjo1NTFBLTA1RTAtRDk0NzElMCMG
// SIG // A1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2Vydmlj
// SIG // ZaCCEfswggcoMIIFEKADAgECAhMzAAACG9CyuAJn93LP
// SIG // AAEAAAIbMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYT
// SIG // AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
// SIG // EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
// SIG // cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1l
// SIG // LVN0YW1wIFBDQSAyMDEwMB4XDTI1MDgxNDE4NDgzMFoX
// SIG // DTI2MTExMzE4NDgzMFowgdMxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
// SIG // ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVs
// SIG // ZCBUU1MgRVNOOjU1MUEtMDVFMC1EOTQ3MSUwIwYDVQQD
// SIG // ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIIC
// SIG // IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAjsWd
// SIG // 52ZZkzB5Xe5g/l2GsOjAz30sg6jVxfFJV+w4xIDVyaI3
// SIG // LO8bIpmzYul3AZHg50UIQ8PrSRZGpQqFkRNu+o3YKJ4g
// SIG // 2uGYBRksHnHYR0uVSCQg58ThkYyeplGX3oAvGRVuPIpQ
// SIG // tAiTsR76A/gdoU7HDwEbb73bJwTyrbKHhR+WaMy9DQHI
// SIG // 4k5Qo4+bZDs0kj76bvhJvdGU+S8zxQBp7UAhjJnFqKxI
// SIG // usSITE7zCCR422ELhkhVVOFqK2w6h1MAvILe76hxRIcP
// SIG // j0SBL2r8O9tx5njU4+tg2rAdU153pmyhqazdpUccYBE9
// SIG // wDRFUd/e9CoWx7TdnUicB+Mai7RT6qse7e5aGqX1B7bn
// SIG // j/ZHvrrfF+BJEIlS9iDXAUgekvXZ+FZmjvLwP+dN+0/c
// SIG // rh++r4e8FknF7EX6IJfnmNeDN/68Z59kbaJ1f+P5mnKY
// SIG // fydCeZmxrGpS0taWkDk36D3jPVZflvxrc+1rhCIlM5v9
// SIG // agLEFI12QiBTfpOBOBr3AGCPk+eH0+latjQajug+2/BD
// SIG // 12qb82500LQytUWT2ota/HYnRgSv1jvZ0/dml1FsxWYz
// SIG // OnCrjfdB/7N6pNySt4vn+PGN6dFLim7kxos+B9WfQPez
// SIG // Ji3fuKyyDAB9zSHPj1Zu8nZfecZJ9um4zj7DFgvJXTDT
// SIG // nG5qlG4ZdbFRa/rrfzkCAwEAAaOCAUkwggFFMB0GA1Ud
// SIG // DgQWBBS2vp93/lxLppNK8OkauJ2AvNmIUDAfBgNVHSME
// SIG // GDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8E
// SIG // WDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
// SIG // b20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0
// SIG // YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUH
// SIG // AQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1p
// SIG // Y3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29m
// SIG // dCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNy
// SIG // dDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsG
// SIG // AQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0B
// SIG // AQsFAAOCAgEAZkU1XxQD4OTM3GTht32TXShIfPBoMfSs
// SIG // FsBQqFOZqLJOxyJOllIBFpmpvOtGNPkC5Z8ldG8aCpvg
// SIG // FNo/jDWeT5FiW53dAj9KnZxpsQ3Pf5fRzSGHRcxEMOdX
// SIG // IVzDJwcZUX0cjfxna7ydNv8eXB/Xk6G6SyrR2OH6S1LH
// SIG // MW11m3UvKF+eLjIPl45rximuDCoEd+ad0lOAXA5/vZOK
// SIG // N5n/ePYeP0LRchZX0Q6H8n/ZmSPMlbli3MO851Q09RmT
// SIG // /ZGHa+/Fdy+WLDrwcYykV9mUy/4TbwKw6FtdR6ZPHxMd
// SIG // Ii1pk8Y2mC/GzCq0LCsH0uTFeQ6Q7Nc3MRmER/3mLWUh
// SIG // baWHgX1FbYchvR22b+Bup+YPR5Q/0BhaaAN6AIBfcGs+
// SIG // u/nJoIByyZKA8cTyCmnUI/4vW6D4vywg3XBFf4f2DwFH
// SIG // y/evsC+58KMl+k2wa05X2kK0T/bCPLhaov9ZXyobawfN
// SIG // OLYGiauKT2FWvbwZzHIFCTxjBww6Pt5uRvCE/jnUcf/x
// SIG // hlOGMn6iKO9Xt49vZTE2SfIBk/34iLTRBJ6H7aGPTTQn
// SIG // za3OfWu1/dRycC6Wl5ons3PjnGXTSKSxXllJPmg6R/ul
// SIG // GonP/UCYoJ6mN+EXjfyDLPXLqsr91+VTG1rYzRCjPwBF
// SIG // AHv4EIwaE0ajCrf75eUGI3+oXU0UP6rloZ8wggdxMIIF
// SIG // WaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqG
// SIG // SIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIw
// SIG // MAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0
// SIG // ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVa
// SIG // Fw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMw
// SIG // EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
// SIG // b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
// SIG // b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
// SIG // IFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
// SIG // MIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwH
// SIG // B9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa
// SIG // 4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZr
// SIG // BxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6
// SIG // xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv62
// SIG // 6GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlw
// SIG // aQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
// SIG // Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I
// SIG // 5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF80
// SIG // 3RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2K26o
// SIG // ElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuv
// SIG // XsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFz
// SIG // ymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZki1ugpoMh
// SIG // XV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/Zc
// SIG // UlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgV
// SIG // GD94q0W29R6HXtqPnhZyacaue7e3PmriLq0CAwEAAaOC
// SIG // Ad0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYB
// SIG // BAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0G
// SIG // A1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNV
// SIG // HSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUF
// SIG // BwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
// SIG // b3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAww
// SIG // CgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
// SIG // YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMB
// SIG // Af8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186a
// SIG // GMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2NybC5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWlj
// SIG // Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUF
// SIG // BwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5t
// SIG // aWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJB
// SIG // dXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQAD
// SIG // ggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pcFLY+Tkdk
// SIG // eLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGh
// SIG // lBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6
// SIG // Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7nd
// SIG // n/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n
// SIG // 4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZ
// SIG // UnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA
// SIG // 0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
// SIG // xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+
// SIG // c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxko
// SIG // JLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVXVAmx
// SIG // aQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/
// SIG // tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM
// SIG // +Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rR
// SIG // nj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N
// SIG // 7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEw
// SIG // ggEBoYHZpIHWMIHTMQswCQYDVQQGEwJVUzETMBEGA1UE
// SIG // CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0w
// SIG // KwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRp
// SIG // b25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNT
// SIG // IEVTTjo1NTFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWlj
// SIG // cm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcG
// SIG // BSsOAwIaAxUAhoV6r49M4GBd41K1RYB1Z0f4zuCggYMw
// SIG // gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
// SIG // Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAN
// SIG // BgkqhkiG9w0BAQsFAAIFAO1+ZWMwIhgPMjAyNjA0MDYx
// SIG // NzAxMjNaGA8yMDI2MDQwNzE3MDEyM1owdDA6BgorBgEE
// SIG // AYRZCgQBMSwwKjAKAgUA7X5lYwIBADAHAgEAAgILWDAH
// SIG // AgEAAgISgzAKAgUA7X+24wIBADA2BgorBgEEAYRZCgQC
// SIG // MSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQow
// SIG // CAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQAEbGow
// SIG // d6V2HWCzRekOpk8ESMsF98nxkK2ZCLDXOloYbx6YEM/L
// SIG // q1hta6DHQnScqJNvUnKJROyu5hg8nik001PTAn3xJgDS
// SIG // ePdaMfmQzH5UtS5u1jWBwXAO0flD2WLOqzR3xRCXkakJ
// SIG // G9qBqnw3sw6XMkw0aV6yuPilUxRPmGA6IWlrLbS1LLj5
// SIG // XdBAIzhjl1DSHUP41a5AUB/V4Z8BJy0IemESkZDBtlIm
// SIG // TWXZ8ZK6rWVZMsVhJz5n/osq+oAEBlgU2GBKbYHL7hE1
// SIG // hdXX3/w9x3mPxaUTox97tLSSy68dgtP4Y5quul9HG3z6
// SIG // heBIyTfMT1h7cfTmj4zGRAoBou2rMYIEDTCCBAkCAQEw
// SIG // gZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
// SIG // bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
// SIG // TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMA
// SIG // AAIb0LK4Amf3cs8AAQAAAhswDQYJYIZIAWUDBAIBBQCg
// SIG // ggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAv
// SIG // BgkqhkiG9w0BCQQxIgQgMZqL/j7QfvFr2ag/WhuwSDEE
// SIG // Hpb7lFawdrt/nbnjGrYwgfoGCyqGSIb3DQEJEAIvMYHq
// SIG // MIHnMIHkMIG9BCAwJRSVuD2jmMcQCFXdLuJAwDpUVNZ6
// SIG // bc6dfJU83Q2LgDCBmDCBgKR+MHwxCzAJBgNVBAYTAlVT
// SIG // MRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
// SIG // ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
// SIG // YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFBDQSAyMDEwAhMzAAACG9CyuAJn93LPAAEAAAIb
// SIG // MCIEIM+TNLS5uIdVYfkztv6rJR/e1svKflF9hJnaOFik
// SIG // yyjOMA0GCSqGSIb3DQEBCwUABIICABhgex1sCoRj+5bu
// SIG // /Xl1nvCaPEj5RrHAsPY2smAAmQv+kgLhqIgbtF1AT32c
// SIG // /lcwtm5VjoPVqkDNXN9DA9G20DNd4MlgM0Acii/i3vK9
// SIG // ZL5dn2FhfCMxTjyDMsSwkstyDyK6xeMM7/WuDcIW7K0y
// SIG // /w5SFFAt+CTdkRzX7N03IIvPs7MKHlczzBiGccBsO7hJ
// SIG // aDHHdHDkzmqD8EexVoQuqkUJkJM84EQL5b0FA+AyqMcu
// SIG // yLsuL9q+egcuVAIUkunNn2a6DeG9Csyw1P9UMBTlTLjW
// SIG // Wrs6yosj7w3Gt9tDPMOKmnLAwdJC4FY5Xd3NCpexyYp9
// SIG // FKiTfxiRHPVGEUpwRQ1QcjuuzU9SyhiCmNBbkDWzRQPP
// SIG // wibW6q+SrcRSHjlMR+DDvhA5+Wo1xnYYcvkz8nJv3Tx6
// SIG // AxlLrke1c6rqeqFBfF+OK+r61V50fYINraEvnApSl/FM
// SIG // cNJE6f0IZ/uhpz9Z85XsebRgVfwLk666Wnv+W77XLQm0
// SIG // N6ncgf+svnUN4OmbdzrOddvy028vsH1GobdN2+2cnjKM
// SIG // BJd7x5nGe8nFNuVGoLq8+H5nnEvhWTNuAhnnB587sjWY
// SIG // iyxQcLwDjAAXctMgwvDHcfYFgwfN84KLsT9ZTkpH81BQ
// SIG // s/BKNoLgj+vZJRiEeGNgAtwWsC4xonOi7SXwO1f04TM8
// SIG // NCco/TmZ
// SIG // End signature block
