import{nativeProtocolRequest as e,isAliveQuery as t,config as n,disconnectNativeHost as s,messageSource as o}from"../models/NativeProtocol.js";import{extStatus as i}from"./Utility.js";import{browserName as a,onNativeMessagingHostSet as c,setpopup as r}from"./InitializeExtension.js";import{onNativeHostRequest as l}from"./NativeHostRequestHandler.js";var h="com.microsoft.defender.browser_extension.native_message_host",g=86400,d="chrome",m="edge",u="firefox";class p{constructor(e){this.hostname=e,this.port=null,this.requestCallbackMap=new Map,this.reconnectAttemptTimeout=1,this.onNativeMessageCallback=this.onNativeMessageCallback.bind(this),this.onDisconnectedCallback=this.onDisconnectedCallback.bind(this),this.sendNativeMessage=this.sendNativeMessage.bind(this),this.reconnect=this.reconnect.bind(this),this.onHandshakeAckCallback=this.onHandshakeAckCallback.bind(this),this.disconnect=this.disconnect.bind(this),this.sendMessage=this.sendMessage.bind(this),this.connect()}static getInstance(e){return p.singletonInstance||(p.singletonInstance=new p(e)),p.singletonInstance}onNativeResponse(e){let t=this.requestCallbackMap.get(e.requestId);if(null!=t){t(e.response,(t,n=e.requestId,s=e.source)=>{this.sendNativeMessage(n,s,t)})&&this.requestCallbackMap.delete(e.requestId)}}onNativeMessageCallback(e){console.log("== onNativeMessageCallback =="),console.log("Message from DefenderHost ["+JSON.stringify(e)+"]"),e.source&&e.source==o.intiatedFromNH?l(e,this.sendMessage):this.onNativeResponse(e)}onDisconnectedCallback(){console.log("== onDisconnectedCallback ==");const e=new n(!1,!1,!1);r(i.Inactive,e),chrome.runtime.lastError&&(console.log("ERROR: Native Host Disconnected ("+chrome.runtime.lastError.message+")"),setTimeout(this.reconnect,1e3*this.reconnectAttemptTimeout))}onHandshakeAckCallback(e){return null==e.urlSensitivityCheck&&(e.urlSensitivityCheck=!1),0==a.localeCompare(d)&&0==e.irmEnabled&&0==e.dlpEnabled||0==a.localeCompare(m)&&0==e.irmEnabled||0==a.localeCompare(u)&&0==e.dlpEnabled?(console.log("Disconnect for now and reconnect after an hour."),this.disconnect(g)):(this.reconnectAttemptTimeout=1,c(e)),!0}initiateHandshake(){var e=null,n="";if(0==a.localeCompare(d)?(e=navigator.userAgent.match(/Chrome\/([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)/),n="Chrome"):0==a.localeCompare(m)?(e=navigator.userAgent.match(/Edg\/([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)/),n="Edge"):0==a.localeCompare(u)&&(e=navigator.userAgent.match(/Firefox\/([0-9]+)\.([0-9]+)/),n="Firefox"),0!=a.localeCompare(d)&&0!=a.localeCompare(m)||5!=e.length){if(0!=a.localeCompare(u)||3!=e.length)return;s=e[1].toString()+"."+e[2].toString()}else var s=e[1].toString()+"."+e[2].toString()+"."+e[3].toString()+"."+e[4].toString();const o=new t(s,n);this.sendMessage(o,this.onHandshakeAckCallback)}connect(){console.log("== Connecting to Native Messaging host =="),this.port=chrome.runtime.connectNative(this.hostname),this.port.onMessage.addListener(this.onNativeMessageCallback),this.port.onDisconnect.addListener(this.onDisconnectedCallback),this.initiateHandshake()}reconnect(){this.reconnectAttemptTimeout=this.reconnectAttemptTimeout<<1,this.reconnectAttemptTimeout>300&&(this.reconnectAttemptTimeout=1),this.connect()}disconnect(e){const t=new s;nativeMessageHost.sendMessage(t,null),this.reconnectAttemptTimeout=e}generateGuid(){return(1e7.toString()+"-"+1e3.toString()+"-"+4e3.toString()+"-"+8e3.toString()+"-"+1e11.toString()).replace(/[018]/g,function(e){return(e^crypto.getRandomValues(new Uint8Array(1))[0]&15>>e/4).toString(16)})}sendNativeMessage(t,n,s){let o=new e(t,n,s);if(console.log("Message to DefenderHost ["+JSON.stringify(o)+"]"),null!=this.port)try{this.port.postMessage(o)}catch(e){console.log("ERROR: Could not send Message to Native Host ("+e.message+")")}else console.log("ERROR: Port Not connected to Native Host (port = null)")}sendMessage(e,t){let n=this.generateGuid();null!=t&&this.requestCallbackMap.set(n,t),this.sendNativeMessage(n,o.intiatedFromExtension,e)}}export var nativeMessageHost;export function setNativeMessagingHost(){nativeMessageHost=p.getInstance(h)}
// SIG // Begin signature block
// SIG // MIIo2AYJKoZIhvcNAQcCoIIoyTCCKMUCAQExDzANBglg
// SIG // hkgBZQMEAgEFADB3BgorBgEEAYI3AgEEoGkwZzAyBgor
// SIG // BgEEAYI3AgEeMCQCAQEEEBDgyQbOONQRoqMAEEvTUJAC
// SIG // AQACAQACAQACAQACAQAwMTANBglghkgBZQMEAgEFAAQg
// SIG // TQO5obHyJ3vFD+iYXzy0ysWPUm3ZSaEC5LdRaPnp7seg
// SIG // gg3DMIIGrTCCBJWgAwIBAgITMwAAAK5/ZNbWLDH+CQAA
// SIG // AAAArjANBgkqhkiG9w0BAQwFADBiMQswCQYDVQQGEwJV
// SIG // UzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
// SIG // MTMwMQYDVQQDEypBenVyZSBSU0EgUHVibGljIFNlcnZp
// SIG // Y2VzIENvZGUgU2lnbmluZyBQQ0EwHhcNMjUwNjE5MTg1
// SIG // NTU4WhcNMjYwNjE3MTg1NTU4WjCBgjELMAkGA1UEBhMC
// SIG // VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
// SIG // B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
// SIG // b3JhdGlvbjEsMCoGA1UEAxMjQXp1cmUgUHVibGljIFNl
// SIG // cnZpY2VzIFJTQSBDb2RlIFNpZ24wggGiMA0GCSqGSIb3
// SIG // DQEBAQUAA4IBjwAwggGKAoIBgQCEcvSWr/qo67Cim1XM
// SIG // timpnEtj5rHnm0af48mDTtLaCwdLNEDfEPfSwwyLQIJY
// SIG // YtKRfyB9XaYKiUNr5ugPoeJ9LAtgIwkJFRfknIFTF5n+
// SIG // fWYMjBV6yNoTk4of+XTzgm4Vv7ueYPHMWygOEaAvBJwL
// SIG // wEc3zoabT0xd8tj7Gr5/MJ9s8Dzlzc4WZdnDTGZDCYLj
// SIG // c6B9Js1CjJVGzvGtqQRI/+Gf7xihho5YqFV+nIuvvivp
// SIG // mGpa/h1RAm1PfjBS/orol/xxP4DAZdLyXzPTDDllSbG9
// SIG // iV9RWH+IAVCDa033CRKFz7cAoihODnMtvGOKjnpebpT+
// SIG // Zp77dJ3ablhwjTaNOYHnNASR1jHytkIpq7QHe1YtowJB
// SIG // vNA4DbUb7jbbp72+/aGKPxBiprw+VEOSQGaEUxmLrmRu
// SIG // SYslI/FyoRv+M9OYhvFGqpyAlXYbjhqvQH9SbbmzrGOT
// SIG // 3+bHhI7aY4j5+vRYhEjf1cImhc94Z6mlH826sxBTynQ6
// SIG // purQnJhV3wcCAwEAAaOCAbkwggG1MA4GA1UdDwEB/wQE
// SIG // AwIHgDAfBgNVHSUEGDAWBggrBgEFBQcDAwYKKwYBBAGC
// SIG // N1sBATAdBgNVHQ4EFgQUvZt5LW7YxIxZozGmGbzpt2/x
// SIG // /uQwRQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jv
// SIG // c29mdCBDb3Jwb3JhdGlvbjEWMBQGA1UEBRMNNDY5OTgx
// SIG // KzUwNTI5MjAfBgNVHSMEGDAWgBTxL7qRFnzefVInMfV6
// SIG // +9VYWWk6PTBvBgNVHR8EaDBmMGSgYqBghl5odHRwOi8v
// SIG // d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9BenVy
// SIG // ZSUyMFJTQSUyMFB1YmxpYyUyMFNlcnZpY2VzJTIwQ29k
// SIG // ZSUyMFNpZ25pbmclMjBQQ0EuY3JsMHwGCCsGAQUFBwEB
// SIG // BHAwbjBsBggrBgEFBQcwAoZgaHR0cDovL3d3dy5taWNy
// SIG // b3NvZnQuY29tL3BraW9wcy9jZXJ0cy9BenVyZSUyMFJT
// SIG // QSUyMFB1YmxpYyUyMFNlcnZpY2VzJTIwQ29kZSUyMFNp
// SIG // Z25pbmclMjBQQ0EuY3J0MAwGA1UdEwEB/wQCMAAwDQYJ
// SIG // KoZIhvcNAQEMBQADggIBAB6iDekXuQ3Ve08WQQMuvXvE
// SIG // RkA0q4Epf158VfZthQeZ5eej1Fv0AWTfxnuO8p49Slkg
// SIG // 811U5Uuruo3aMthdfMqgv6Y2lZfX35mrcOUNu3UviCqY
// SIG // 0pUQmFdz30hpHca3uAen6vVzXVuiNa5yNJ5rG8omFx5m
// SIG // jWHHysIIOyCuBc21scassJN0xjom2lX6sMHGh7XW/aah
// SIG // 0CbecyaowoxRWYPQFrFDUq5cplijNgyirPXlCrJXBNTZ
// SIG // kIFPtiBSJJMoXlvkU+1H0xVcJ6kUw9qOoAdxNuI5hAvL
// SIG // GIft1tvfL3mljW4zFWjvhgkTszpQNbgqEJEs6W9c/y3C
// SIG // Z1hoGOGFcuMgLSkrzz9FjR6r8QDwvu5gmAC4eaZQv5Vm
// SIG // EF0DK56h8UiIIfMdEQCuOAUVZZBuLGE5ARX8anViTAyA
// SIG // WrbyqpeGwQtgKwJGPwrBX+cSEFeHJvONbN/EyhgQdFK+
// SIG // C8b0SC/idqhurBJCipHgNeC6SpHyxFBd7vOYsj2S3Ux5
// SIG // aVf4yKLyy3LtnAzW/OglurPTlKY35UNep8cnRXziuIj8
// SIG // 2K9DxmQI2tfCpbNrP6gf5893tZ3z/zojMIy0PcmgGSgt
// SIG // euCJajA2sKym9FaRed5UGXFKzUVNBDbd5YLL4rc92U+V
// SIG // oUhOJ5ZwPpIlhNCShERT/jRRg0cGjUQ+iYF1mdIbiArq
// SIG // MIIHDjCCBPagAwIBAgITMwAAAAKyxJOIeFns0wAAAAAA
// SIG // AjANBgkqhkiG9w0BAQwFADBbMQswCQYDVQQGEwJVUzEe
// SIG // MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSww
// SIG // KgYDVQQDEyNNaWNyb3NvZnQgUlNBIFNlcnZpY2VzIFJv
// SIG // b3QgQ0EgMjAyMTAeFw0yMTA5MDIxNzQxMTlaFw0zNjA5
// SIG // MDIxNzUxMTlaMGIxCzAJBgNVBAYTAlVTMR4wHAYDVQQK
// SIG // ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMzAxBgNVBAMT
// SIG // KkF6dXJlIFJTQSBQdWJsaWMgU2VydmljZXMgQ29kZSBT
// SIG // aWduaW5nIFBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIP
// SIG // ADCCAgoCggIBAKXd/Sy91nFgseVJOFgeRhVxrcahyp1Y
// SIG // GSN0FpOEgEREVb3ND/QgI7I0yd7XG6OE8Vomr5FMxvK8
// SIG // TvJ4Lc6LP9BDz2GSa1M0LlzHKX757/24C0ZndzccA1qQ
// SIG // i00+BmmOr4plmxRzTFv4Phdw8yBPF9GDvClqV8ASvvbi
// SIG // tfjaD7dVPOFLb7N7fvt/qWogGN5eis0FXCqVJdmPZZaX
// SIG // 2h4iG0otsAhfq8yvSlJ0YwO4i5GDeLQwTsMN1Rf2UAHQ
// SIG // KCUYkFsLSQ0mqbaRbDZhB+2pFL/q/c2a6hlHLnapYyfw
// SIG // lNFXkDhwAFWEzfwFHER2oR42UayfN9tsO/p2tWk33Crn
// SIG // HdndJDrIZ6oQ3D+Ngol/TR8BAgXCIM6se6YlLDTsxRwh
// SIG // 9QUDq7KVhKy58HGKJUqwgIW0E7cvlzUl0Hft/ebhALZy
// SIG // FDkhof9C5Cq4c/486XLjQq0nbuKsFNhQU0yvABR3eohw
// SIG // 63Kps66Uma48oE0JmqOxmzrPvrITYcsnByKleiHn+4yq
// SIG // +Ts/KrtqkQwQcuikMPrZwXCtsYkxMUyUn8gr8oew22WD
// SIG // eIQECAM1Cz9TcdJadsrToKqXQa2bAn/AABAYyogPPONf
// SIG // GvojTI3DlYD42etMa/gPeZJavX+z7x8d/4eYBnJ9WFSi
// SIG // 9q0v+vLOGc3fyM2KQtq5eVbHX5rVyWc6bJ35AgMBAAGj
// SIG // ggHCMIIBvjAQBgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4E
// SIG // FgQU8S+6kRZ83n1SJzH1evvVWFlpOj0wVAYDVR0gBE0w
// SIG // SzBJBgRVHSAAMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93
// SIG // d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBv
// SIG // c2l0b3J5Lmh0bTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBi
// SIG // AEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB
// SIG // /zAfBgNVHSMEGDAWgBQODLFkab0tsdVrJqZH6lZOgMPt
// SIG // ijBmBgNVHR8EXzBdMFugWaBXhlVodHRwOi8vd3d3Lm1p
// SIG // Y3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQl
// SIG // MjBSU0ElMjBTZXJ2aWNlcyUyMFJvb3QlMjBDQSUyMDIw
// SIG // MjEuY3JsMHMGCCsGAQUFBwEBBGcwZTBjBggrBgEFBQcw
// SIG // AoZXaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
// SIG // cy9jZXJ0cy9NaWNyb3NvZnQlMjBSU0ElMjBTZXJ2aWNl
// SIG // cyUyMFJvb3QlMjBDQSUyMDIwMjEuY3J0MA0GCSqGSIb3
// SIG // DQEBDAUAA4ICAQBin7PMBnXjnIJ0x++LnudLDWWnZ8dZ
// SIG // mJ14DuZfUss/doUThLAM4crrHaTbJoulUUELNd2AnOpX
// SIG // /Z4tenUMT3sjYIdPYyJfIYWPRqfI6Nbz+JVK7RRvn2nl
// SIG // 5EEMIuRE6UKS9ZGBbf02a7sb04E/7BN/NhhrmtS/tVFj
// SIG // fRrrVh9zXku45rqWuCwUTzg3EqxKQ8OGbtjBQtq/Syb/
// SIG // clm5BHsoh3XhMnb9VLv3G1duNf90FL5/o88XZ4L18nx1
// SIG // lfky2nllY4HIA8PK8AarqAW4iKSTA3EGqn8s/47WtQKT
// SIG // +qED2YbZXVOYL+L7vQDCnFbwhgAx6ucuMz7Ae1rqibg3
// SIG // AjsC7U5M3oA/vqAHDKDA3mdM5D6L/ZEdQgaG20HhUOSQ
// SIG // +CiQD3TyHSiVCfVMuTv83IiKCni3LW/23tHC2tbN57rl
// SIG // hMcoyjIi+IVd7j7s41MFBaDwJrmfXn/YM+lR/5QqvO7z
// SIG // WAbbr/XU531v3jr/jBilmrqt6U/b7y8TXyA9nYxV9iSM
// SIG // FmcbyIi2xgdcAHhxnpXcvcvyFWET6YiJiyeSJZwwJv8g
// SIG // wXiBF+Zh0IHArl6KVsbAdsATuP1TCEBpPynXZmkviIEW
// SIG // Ptnv315ZjTC7nPoOpSnOVaO7wZztrOefZunI5fBxw7mG
// SIG // 1oyoRnADZawiFsVo9J/cDu15ErRCfDQRhwSiBTGCGm0w
// SIG // ghppAgEBMHkwYjELMAkGA1UEBhMCVVMxHjAcBgNVBAoT
// SIG // FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEzMDEGA1UEAxMq
// SIG // QXp1cmUgUlNBIFB1YmxpYyBTZXJ2aWNlcyBDb2RlIFNp
// SIG // Z25pbmcgUENBAhMzAAAArn9k1tYsMf4JAAAAAACuMA0G
// SIG // CWCGSAFlAwQCAQUAoIGuMBkGCSqGSIb3DQEJAzEMBgor
// SIG // BgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEE
// SIG // AYI3AgEVMC8GCSqGSIb3DQEJBDEiBCDM7mCbJzff2JXI
// SIG // Tdab4NVUQj8zsgallIsitk22CMLuxTBCBgorBgEEAYI3
// SIG // AgEMMTQwMqAUgBIATQBpAGMAcgBvAHMAbwBmAHShGoAY
// SIG // aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3
// SIG // DQEBAQUABIIBgBzvaYd3q6ewpOO4cbOwkZZi7fhSuMwv
// SIG // 2z4TFoJi4abi6ix7Du7Gl7F23mNpcFd5XfJteH+/92Yu
// SIG // c6BPh6VXXHN2zdsJhXAerglhuc28tYq2KunjimKEAHYY
// SIG // Uq7D6RkMVehVnYoDYvv917qV1mjCf46DNskCVNlrVYNU
// SIG // Yi2ITNzO1YpeD6qcej4jYdzVsE38D3imcCrnJBFRhkfH
// SIG // 7Gbt98ThsFSbLHMWwssSeYhYiuJ9dmxv8NJ5hLUmVQKK
// SIG // 8y0Sf8zP3jiBucHf/+/SaIUNlqt+IOAueR+nrT37L7d8
// SIG // 6F7Z63z3cnI9ksROAEbXbc1argQ3IYdyLgOC1p+2xIg2
// SIG // POLM/KqzW29gj1besI70OoL5dZINNb0jzLf5guR27E8h
// SIG // WQ2hqKNY41Gym0IWEYd3PWrpeKcTcUlEEpKw4v1IGwgU
// SIG // hY2cuD1cj95FNzHbqPJExaF1KDfOPbPDcP8PS9ZfSB85
// SIG // 85tEx/JMVBkfvt7czHjKwp4kxFZCL7fwThZ6LCeo46GC
// SIG // F5QwgheQBgorBgEEAYI3AwMBMYIXgDCCF3wGCSqGSIb3
// SIG // DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUDBAIBBQAw
// SIG // ggFSBgsqhkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYK
// SIG // KwYBBAGEWQoDATAxMA0GCWCGSAFlAwQCAQUABCDVe+Kf
// SIG // 928ieyCH8E13Km70vpx+oM3hNdjF9X4gTcxfTAIGabhY
// SIG // rydxGBMyMDI2MDQwNjIwMjU1MC42NDdaMASAAgH0oIHR
// SIG // pIHOMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
// SIG // aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
// SIG // ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQL
// SIG // ExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScw
// SIG // JQYDVQQLEx5uU2hpZWxkIFRTUyBFU046QTQwMC0wNUUw
// SIG // LUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
// SIG // YW1wIFNlcnZpY2WgghHqMIIHIDCCBQigAwIBAgITMwAA
// SIG // AijwpYfX88geQAABAAACKDANBgkqhkiG9w0BAQsFADB8
// SIG // MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
// SIG // bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWlj
// SIG // cm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
// SIG // b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNjAy
// SIG // MTkxOTQwMDZaFw0yNzA1MTcxOTQwMDZaMIHLMQswCQYD
// SIG // VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
// SIG // A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
// SIG // IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQg
// SIG // QW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hp
// SIG // ZWxkIFRTUyBFU046QTQwMC0wNUUwLUQ5NDcxJTAjBgNV
// SIG // BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Uw
// SIG // ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCu
// SIG // jvbk/sqcCSReZaJfCuf1NwRcc7XknhE6wkLofkNj1mxE
// SIG // Ag35qy2xcFjgjartVvA09W8QHcpyMqVSXOTxNHJsmk0q
// SIG // P2CDLvUAulWg7aS5oBORpEX1oz3n0R2nPqeH0IHK1zJx
// SIG // jxaHW21AbuZ0Z+wM3WYNzkBlcHmVe03ZG7rlk28h72r5
// SIG // P5ME8FGpFmYW5Hl7psKbgLEfrYAitpttsb+sZsBUI+hM
// SIG // Kl4uLJYotKyZv1ewOIinBfRU8QosivjofaBezUf9NdV+
// SIG // iGrWh321WnSsK3A/Jl6GLtbSWXcJWULgbxuqnobPK+Yl
// SIG // B3174TMWTgX4YWjG7o0Otz/pjHNCKBbB788dynhLdGY6
// SIG // B08E9+4SGrRpsty4iJHOydHCA5M4i5yYRwsdut+gmvxI
// SIG // pT8yNXJcjJCg0vO8mv/nFY9Wytv2qmCtCFFivGUWqU20
// SIG // /sUeRooQZGiQOJQn095Cj3isIsvRP8KU7hN/EDI8HVsb
// SIG // /NPzMFLvRznrRnj0TOnDiOTUcnYwmk+XfoS1owskcCCC
// SIG // wHnbC00D58z83y7K5ZJB745hcn4CE2nR3e6RGsr42y5q
// SIG // tt6Mdz/s7MTnDS2UmVHWX1X/HZe3UlX8gj/t63L50xIP
// SIG // qkRCBEdM1ADNUaSfo9OQiKb/bj1diZCGTfEDUBBLop1m
// SIG // hkwIF82faplV2busZ+U4kQIDAQABo4IBSTCCAUUwHQYD
// SIG // VR0OBBYEFKrJpYz48tzouvVkBVthASFpQ93DMB8GA1Ud
// SIG // IwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1Ud
// SIG // HwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0
// SIG // LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUyMFRpbWUt
// SIG // U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEF
// SIG // BQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cu
// SIG // bWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9z
// SIG // b2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSku
// SIG // Y3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYI
// SIG // KwYBBQUHAwgwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3
// SIG // DQEBCwUAA4ICAQCQ6NfLmrRahgVtgWg383GaS07fHyod
// SIG // 6bhcUONt2tet+6BaNuH0r7ABkVHheOpxBdrUrOEYVEaI
// SIG // ii9dK3cuZLNmp1iUAx/VbmOZYl7xz+tNrjCWqrg1jQmq
// SIG // 0oRB8iE4QJpwNhGP67oY5huYIU0D4lhDoahqfgKJn/0B
// SIG // k+9UKDPw5XlUYmreFmJlj9YQzcPPep8MxBXxh/Y5I7vQ
// SIG // eRaW5SjtiLQOLRk3ggvraDs5Sf49MJV6/BwxXC2rvUfE
// SIG // FX6SUDooqKIE9NgVIRq0RZu7Ot0i0Is+HvPP0hB6KwOx
// SIG // Mg1SWKOfTtFpWpdo8MJvgKCHkPpXEzgprP+pyIHuO7gV
// SIG // RlSTsbYBFLh2yId/itM4uYL0R+2SSBBTpSSRthrGuEmE
// SIG // lI5BCHMxzMg/oqHSPwZAIAkM2C4xxi0St7qMuA+m+ZzF
// SIG // YkfoF41QoSJn+HjqhqWYQ0m/SO9/KnJRJJUwMd5TiMnj
// SIG // Z+E/DJiUry5udiWyQpvfj2hQFI0djhahoAXDazeEciLF
// SIG // 2uEnTur9UfjcwOun/oMY+ULftnOi2jKLMrreV097akzz
// SIG // /JxpnDgYJU/tgU7fQflg7IqiL9+0276+joQHo21mVeY5
// SIG // YD8Kh/kUaY6Jm/OTM88G7evTz/qnRumxovTjMStvpbAH
// SIG // NRhmSTdIPTV32CyuxDKS/V5a5iwA+f9ViBo+wjCCB3Ew
// SIG // ggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJ
// SIG // KoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYD
// SIG // VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
// SIG // MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
// SIG // MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmlj
// SIG // YXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIy
// SIG // NVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMx
// SIG // EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
// SIG // ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
// SIG // dGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
// SIG // bXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4IC
// SIG // DwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3u
// SIG // nAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VT
// SIG // cVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aO
// SIG // RmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlh
// SIG // AnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S
// SIG // /rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc
// SIG // 6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1o
// SIG // O5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbni
// SIG // jYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
// SIG // XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYr
// SIG // bqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M
// SIG // 269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFph
// SIG // AXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6Cm
// SIG // gyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr
// SIG // 9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfH
// SIG // CBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQAB
// SIG // o4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkr
// SIG // BgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4w
// SIG // HQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwG
// SIG // A1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYB
// SIG // BQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9w
// SIG // a2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUE
// SIG // DDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMA
// SIG // dQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw
// SIG // AwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
// SIG // zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3Js
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9N
// SIG // aWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYB
// SIG // BQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3
// SIG // Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0Nl
// SIG // ckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsF
// SIG // AAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5O
// SIG // R2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts
// SIG // 0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp
// SIG // 4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRX
// SIG // ud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFd
// SIG // PSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZ
// SIG // QhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzs
// SIG // kYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCr
// SIG // dTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5
// SIG // JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
// SIG // GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdU
// SIG // CbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3
// SIG // Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzba
// SIG // ukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRb
// SIG // atGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNT
// SIG // TY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNNMIICNQIB
// SIG // ATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEl
// SIG // MCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0
// SIG // aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkE0
// SIG // MDAtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQg
// SIG // VGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoD
// SIG // FQB1rbmFkzS7qAK1Oav08AUnhbNIUqCBgzCBgKR+MHwx
// SIG // CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
// SIG // MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
// SIG // b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jv
// SIG // c29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqGSIb3
// SIG // DQEBCwUAAgUA7X6DxTAiGA8yMDI2MDQwNjE5MTEwMVoY
// SIG // DzIwMjYwNDA3MTkxMTAxWjB0MDoGCisGAQQBhFkKBAEx
// SIG // LDAqMAoCBQDtfoPFAgEAMAcCAQACAideMAcCAQACAhKJ
// SIG // MAoCBQDtf9VFAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwG
// SIG // CisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMB
// SIG // hqAwDQYJKoZIhvcNAQELBQADggEBAEDEE4iBrBknxgKS
// SIG // H7ndjHid7jtfPlfThdJ4LRw6SlnrXvuyomIbpy6Nxglc
// SIG // I+y1BWRopUvNkEwA7T/rCyG7kd62S5ZHH5+3FJWyaRbL
// SIG // Q6zcfZDTLOfwLfbXZ5X3lezqaHjjic6F38eSG0XU5lgP
// SIG // 7PCrf9uxDT4jCok7p102dINGM4wz80dEke4JSmDaV0Ek
// SIG // rONwjXeNV1lCweRn2bR+6leWI9MtC0ig9b+DVkV6pCGb
// SIG // szl7kZxK43Z8WTvl5BkrPt+lgxC4r+lltv+itHVkM9q/
// SIG // 6Ds/+eRWyKNL0w9l4H0dl5dhfWfepnbEhq33NWh4V418
// SIG // wiF0X0FdTxKMPtWRYu4xggQNMIIECQIBATCBkzB8MQsw
// SIG // CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
// SIG // MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
// SIG // b2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
// SIG // ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAijwpYfX
// SIG // 88geQAABAAACKDANBglghkgBZQMEAgEFAKCCAUowGgYJ
// SIG // KoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8GCSqGSIb3
// SIG // DQEJBDEiBCAa7P2vbtzn/MbBy8NZ+LVx7dzdvXEF2q8G
// SIG // olt6eEXQ3TCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQw
// SIG // gb0EIFWxikZRYGNf4oEVZK1eT45H+3GQ3/qxV75VwuBt
// SIG // +iLXMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
// SIG // BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
// SIG // HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEm
// SIG // MCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
// SIG // IDIwMTACEzMAAAIo8KWH1/PIHkAAAQAAAigwIgQgsXPW
// SIG // xSwHapBmOW4LNurBD7QQsamM0dE45TN0w1QaCHMwDQYJ
// SIG // KoZIhvcNAQELBQAEggIAQaZJiTHduQakyXQo+/9Eol6k
// SIG // +ilnRsqw2PyVVpEIMM8+1UNZp6pp0cSyJzbTvQoGqh2K
// SIG // N5DhHTCLRmP3BEhdfEzVkP1+HlPskPHndzQuW6hxBA3H
// SIG // AxiOejxZ4ME/lkcQ9Wp8GsBXqG9/TMbjkSAMJ3Rd4LMc
// SIG // si7Po0jsT3TUK9xoR23lhnFMHCFaCSggIrl+uZQZ5Cgj
// SIG // L8fTpLGgMNhWC54BvpPrXJkJNSd159UXHqqpI8Y5pw+J
// SIG // dbzGyqEM3cWHMJX2YK/hqLm+7GLDQfGQVqJch3Ci4gsT
// SIG // +b3ZSMxqDyRB7CuQp0sUpOJ0nvy84unl0amdaIXhHU75
// SIG // iu/Hzrrr5pdNORHaVr8toV+xDPlDLGz1Y8ywc/fZFwyh
// SIG // PbNtR/RIZqn8IIiWUlprrHiy+4TCU/SkRwVlVucscmSL
// SIG // U2IX/aFyRP7fNCPmN6tM3K7ra7pqscDWyoaZNieVpcg+
// SIG // 25eYCRLsaLlTrj3g14FMhkTTnazWgfF6RU8QjcO5shUO
// SIG // s2rVIBjlk1bMpvQE0rDF3/+P8K4FagpEGlPtNOIV3icR
// SIG // OBTNntPBN7l0Z/QqWuDYQun4mOppiMGeDshk8kr9y9KO
// SIG // qV0cozwpj2pP3IXPj2azYrjf2W/gD+iyMRZnLMHdFgMu
// SIG // 1RWCNtPhgEVTHqyM+T3W1h5phlNS+3kUYdjuntpapH0=
// SIG // End signature block
