"""Adams/Car .cmd generation, behind an approval gate.

The gate is not a formality.  A mass properties command overwrites values a
vehicle dynamics engineer may have tuned by hand, and the failure is silent:
the model still runs, it just handles differently.  So `preview` renders the
exact change set and hashes the exact file that would be written; `export`
refuses to run unless it is handed that hash back.  A model cannot invent the
token, it can only copy it from a preview the human has seen.

The command syntax below follows the Adams command language shape:

    marker modify marker_name = <cm> location = x, y, z
    part modify rigid_body mass_properties &
        part_name = <part> & mass = <kg> & ... & cm_marker = <cm>

Verify it once against your own Adams release's command reference before the
first production use; releases have added and renamed arguments.  If your site
uses a different flavour, edit assets/cmd_template.txt rather than this file.
"""

import hashlib

from .envelope import CmcError
from . import config, transform, units


def build_rows(rolled, adams_map, tp, units_profile, include_inertia):
    parts = adams_map.get("parts") or {}
    ignore = set(adams_map.get("ignore") or [])

    unmapped = [b["name"] for b in rolled["buckets"]
                if b["name"] not in parts and b["name"] not in ignore]
    if unmapped:
        raise CmcError(
            "E_UNMAPPED_BUCKET",
            f"{len(unmapped)} alt yapının Adams karşılığı tanımlı değil.",
            "adams_map.json içinde her alt yapıyı bir Adams parçasına eşleyin, "
            "veya bilerek dışarıda bırakıyorsanız 'ignore' listesine ekleyin.",
            unmapped=unmapped,
        )

    rows = []
    for bucket in rolled["buckets"]:
        name = bucket["name"]
        if name in ignore:
            continue
        mapping = parts[name]
        part_name = mapping["part"] if isinstance(mapping, dict) else str(mapping)
        cm_marker = (mapping.get("cm_marker") if isinstance(mapping, dict) else None) \
            or f"{part_name}.cm"

        cg_adams = transform.point(tp, bucket["cg_mm"])
        row = {
            "bucket": name,
            "part": part_name,
            "cm_marker": cm_marker,
            "mass_kg": bucket["mass_kg"],
            "cg_catia_mm": list(bucket["cg_mm"]),
            "cg_adams_mm": list(cg_adams),
            "inertia": None,
            "inertia_skip_reason": None,
        }

        if not include_inertia:
            row["inertia_skip_reason"] = "profile_incomplete"
        elif not bucket["inertia_complete"] or not bucket["inertia_tensor_cg"]:
            row["inertia_skip_reason"] = "bucket_inertia_incomplete"
        else:
            rotated = transform.tensor(tp, bucket["inertia_tensor_cg"])
            row["inertia"] = transform.to_adams_products(tp, rotated)
        rows.append(row)
    return rows


def render_cmd(rows, meta, tp, units_profile):
    lines = [
        "! ------------------------------------------------------------------",
        "! generated by cmc {}".format(meta.get("cmc_version", "")),
        "! vehicle       : {}".format(meta.get("vehicle")),
        "! variant       : {}".format(meta.get("variant")),
        "! revision      : {}".format(meta.get("revision")),
        "! run id        : {}".format(meta.get("run_id")),
        "! source        : {}".format(meta.get("source_document")),
        "! source sha256 : {}".format(meta.get("source_sha256")),
        "! measured by   : {} at {}".format(meta.get("measured_by"), meta.get("measured_at")),
        "! catia         : {}".format(meta.get("catia_version")),
        "! work mode     : {}".format(meta.get("work_mode")),
        "! transform     : {}".format(tp["name"]),
        "! units         : mm, kg, kg*mm^2",
        "! inertia ref   : {} / product sign {}".format(
            units_profile.get("inertia_ref"), units_profile.get("inertia_product_sign")),
        "! ------------------------------------------------------------------",
        "",
    ]
    for row in rows:
        x, y, z = row["cg_adams_mm"]
        lines.append("! {} -> {}".format(row["bucket"], row["part"]))
        lines.append("marker modify &")
        lines.append("   marker_name = {} &".format(row["cm_marker"]))
        lines.append("   location = {:.6f}, {:.6f}, {:.6f}".format(x, y, z))
        lines.append("part modify rigid_body mass_properties &")
        lines.append("   part_name = {} &".format(row["part"]))
        lines.append("   mass = {:.6f} &".format(row["mass_kg"]))
        if row["inertia"]:
            it = row["inertia"]
            lines.append("   ixx = {:.6f} &".format(it["ixx"]))
            lines.append("   iyy = {:.6f} &".format(it["iyy"]))
            lines.append("   izz = {:.6f} &".format(it["izz"]))
            lines.append("   ixy = {:.6f} &".format(it["ixy"]))
            lines.append("   izx = {:.6f} &".format(it["ixz"]))
            lines.append("   iyz = {:.6f} &".format(it["iyz"]))
        else:
            lines.append("!  atalet yazilmadi: {}".format(row["inertia_skip_reason"]))
        lines.append("   cm_marker = {}".format(row["cm_marker"]))
        lines.append("")
    return "\n".join(lines) + "\n"


def token_of(cmd_text):
    return hashlib.sha256(cmd_text.encode("utf-8")).hexdigest()[:16]


def render_preview(rows, cmd_text, diff_data, landmark_check, meta):
    out = []
    out.append("DEGISIKLIK ONIZLEMESI")
    out.append("=" * 72)
    out.append("Arac    : {} / {} / {}".format(meta.get("vehicle"), meta.get("variant"), meta.get("revision")))
    out.append("Kaynak  : {}".format(meta.get("source_document")))
    out.append("Donusum : {} (dogrulama max hata {:.3f} mm)".format(
        meta.get("transform_name"), landmark_check.get("max_abs_error_mm", 0.0)))
    out.append("")
    out.append("{:<24} {:<28} {:>12} {:>10}".format("ALT YAPI", "ADAMS PARCA", "KUTLE [kg]", "ATALET"))
    out.append("-" * 78)
    for row in rows:
        out.append("{:<24} {:<28} {:>12.3f} {:>10}".format(
            row["bucket"][:24], row["part"][:28], row["mass_kg"],
            "var" if row["inertia"] else "yok"))
        out.append("{:<24} {:<28} X {:>10.3f}  Y {:>10.3f}  Z {:>10.3f}".format(
            "", "(Adams CG mm)", *row["cg_adams_mm"]))
    out.append("")

    if diff_data and diff_data.get("has_previous"):
        out.append("ONCEKI REVIZYONA GORE ({})".format(diff_data["previous"]["revision"]))
        out.append("-" * 78)
        out.append("Toplam kutle farki : {:+.3f} kg".format(diff_data["delta_total_mass_kg"]))
        dx, dy, dz = diff_data["delta_total_cg_mm"]
        out.append("Toplam CG farki    : X {:+.3f}  Y {:+.3f}  Z {:+.3f} mm".format(dx, dy, dz))
        for row in diff_data["buckets"]:
            if row["change"] == "unchanged":
                continue
            if row["change"] in ("added", "removed"):
                out.append("  {:<24} {}".format(row["bucket"][:24], row["change"]))
            else:
                cx, cy, cz = row["delta_cg_mm"]
                out.append("  {:<24} {:+.3f} kg   CG {:+.2f} / {:+.2f} / {:+.2f} mm".format(
                    row["bucket"][:24], row["delta_mass_kg"], cx, cy, cz))
        out.append("")
    else:
        out.append("Onceki revizyon yok, karsilastirma yapilamadi.")
        out.append("")

    out.append("Yazilacak dosya: export.cmd  ({} satir)".format(len(cmd_text.splitlines())))
    out.append("Onay kodu      : {}".format(token_of(cmd_text)))
    return "\n".join(out) + "\n"


def prepare(run_id, rolled, meta, adams_map, transform_profile, units_profile, diff_data):
    tp = transform.load(transform_profile)
    landmark_check = transform.verify_landmarks(tp)
    include_inertia = units.inertia_ready(units_profile)

    rows = build_rows(rolled, adams_map, tp, units_profile, include_inertia)
    cmd_meta = dict(meta)
    cmd_meta["transform_name"] = tp["name"]
    cmd_text = render_cmd(rows, cmd_meta, tp, units_profile)
    preview_text = render_preview(rows, cmd_text, diff_data, landmark_check, cmd_meta)

    return {
        "rows": rows,
        "cmd_text": cmd_text,
        "preview_text": preview_text,
        "token": token_of(cmd_text),
        "landmark_check": landmark_check,
        "include_inertia": include_inertia,
    }


def write(run_id, cmd_text):
    path = config.run_dir(run_id) / "export.cmd"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cmd_text, encoding="utf-8")
    return path
